### ISSUE TITLE
Test the forked version

### ISSUE THREAD

**Issue by oceandie** [JMMP-Group/CDFTOOLS#2]
This issue is concerned with testing that the forked version of CDFTOOLS can be succesfully compiled and used and, in case, make the needed changes to `dev_jmmp` branch.

**Comment by oceandie** [comment]
I just tested the forked version and I can succesfully compile it with the following `make.macro`:

```
NCDF =  -Wl,-rpath,/project/ukmo/rhel6/netcdf4/ifort_composerxe/lib/ -I/project/ukmo/rhel6/netcdf4/ifort_composerxe/include/ -L/project/ukmo/rhel6/netcdf4/ifort_composerxe/lib -lnetcdff

F90=ifort
MPF90=mpif90

#Use first set of FFLAGS for testing code
NC4 = -D key_netcdf4 #-D key_CMIP6
FFLAGS= -O3 -fpe0 $(NCDF) $(NC4) -assume byterecl -convert big_endian -g -traceback

#-heap-arrays
LMPI=-lmpich
OMP=-openmp
```

However, if I use `NC4 = -D key_netcdf4 -D key_CMIP6` , then the compilation is suddenly aborted.

**Comment by DaveStorkey** [comment]
The compilation problem with key_CMIP6 is to do with missing variable declarations and definitions in modcdfnames_CMIP6.h90. I've fixed these now in my clone, but I need permission to write to the repository to push these back.

**Comment by oceandie** [comment]
Thanks @DaveStorkey, will give the full permission both to you and @dcalve now!

**Comment by DaveStorkey** [comment]
I've pushed those bug fixes now. The code now builds under scitools with key_CMIP6 and I've managed to get cdf_xtrac_brokenline to run and give sensible results.

**Comment by oceandie** [comment]
[like]  Diego Bruciaferri reacted to your message:
________________________________
